Batmanscode railway 1 (#11)
* add gunicorn 20.1.0

* Create deploy.template.yaml

* Create gunicorn.conf.py

* Create Procfile

* add digital ocean deploy button

* update how to run locally

* moved `name` up

* move everything under `spec`

* Update deploy.template.yaml

changed to use `git` instead of `github` since there was a github authentication error when using the deploy button

* upgrade klib from 2.0 to 2.3

* scikit-learn==0.23.2 to fix the deployment problem

pycaret needed this

* move scikit-learn to the top

* Add missing datetime, assign_cluster_labels imports

* Update requirements.txt

* klib (1.0.1) no longer uses scikit-learn
* scikit-learn removed since pycaret will install it. pycaret and klib both used scikit-learn and there were version issues sometimes so it was used as a temporary work around

* Delete .do directory

* Delete Procfile

* Delete gunicorn.conf.py

* remove do button and gunicorn command

* Create Procfile

for railway.app

* Delete Procfile

revert last commit

* Create Procfile

for railway.app

* Update Procfile

forgot to add "web"

* Update requirements.txt

railway build failed and was missing python-multipart

* Update Procfile

* don't specify port
* railway built successfully but there was a port issue

* Update Procfile

railway.app needs apps to have a $PORT set as a variable

* Update Procfile

Error: Got unexpected extra arguments (port 8080)

* Update Procfile

this seems like the correct way to set a variable in uvicorn

* Update Procfile

UVICORN_PORT doesn't have to be set, any environment variable under that will be passed to port

* Update Procfile

changes didn't work - going back to the full command without any variables

* Update Procfile

got help from discord, trying again with $PORT and deleting variables from the railway.app menu

* temporarily added cors middleware

https://fastapi.tiangolo.com/tutorial/cors/?h=%20cors#use-corsmiddleware

* can now read CSV from a string

* update funcion docstrings

the input CSV can now optionally be a string

* removed reading a string into a dataframe

* no idea why but even files were no longer working so just removed it
* updated error handling

* update docstring

* add end points that take csv strings instead of files

* add `from typing import Optional`

* remove unnecessary "/" at the end of endpoint names

* update docstrings

* pandas can create a dataframe from a csv file or a string

* change from query to body parameters

* body params instead of query for `auto-clustering-csv-string`

* remove commas for `AutoClusteringString`

* body params instead of query for `clustering-csv-string`

* import Body

* make optional params show up as optional in fastapi

`List[str]` to `Optional[List[str]]`

* remove endpoints that can take strings instead of csv

they can't work

* add demo railway.app link and git clone command

* remove docs that were used for uploading csv as a string

forgot to remove these when the functions they were used in were removed

Co-authored-by: Nivethan <arnive19@gmail.com>